import { Router } from 'express';
import auth from './auth.routes.js';
import publicRoutes from './public.routes.js';
import kiosk from './kiosk.routes.js';
import members from './members.routes.js';
import plans from './plans.routes.js';
import attendance from './attendance.routes.js';
import coaches from './coaches.routes.js';
import programs from './programs.routes.js';
import progress from './progress.routes.js';
import engagement from './engagement.routes.js';
import payments from './payments.routes.js';
import pos from './pos.routes.js';
import equipment from './equipment.routes.js';
import incidents from './incidents.routes.js';
import inquiries from './inquiries.routes.js';
import community from './community.routes.js';
import notifications from './notifications.routes.js';
import messages from './messages.routes.js';
import reports from './reports.routes.js';
import settings from './settings.routes.js';
import auditRoutes from './audit.routes.js';
import platform from './platform.routes.js';

const api = Router();
api.get('/health', (req, res) => res.json({ ok: true, time: new Date().toISOString() }));
api.use('/auth', auth);
api.use('/public', publicRoutes);
api.use('/kiosk', kiosk);
api.use('/members', members);
api.use('/plans', plans);
api.use('/attendance', attendance);
api.use('/coaches', coaches);
api.use('/programs', programs);
api.use('/progress', progress);
api.use('/engagement', engagement);
api.use('/payments', payments);
api.use('/pos', pos);
api.use('/equipment', equipment);
api.use('/incidents', incidents);
api.use('/inquiries', inquiries);
api.use('/community', community);
api.use('/notifications', notifications);
api.use('/messages', messages);
api.use('/reports', reports);
api.use('/settings', settings);
api.use('/audit', auditRoutes);
api.use('/platform', platform);

export default api;
